// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP3QNpm7ns5YzD4YSEUpKaShElhTtufuw',
    appId: '1:961689273755:web:72f1e76028845c8f3b4d3e',
    messagingSenderId: '961689273755',
    projectId: 'easytravel-b7a06',
    authDomain: 'easytravel-b7a06.firebaseapp.com',
    storageBucket: 'easytravel-b7a06.appspot.com',
    measurementId: 'G-P4TFLZL7ZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS6Lu0mUVeMyT_ev-in0tmXV6guitNjNA',
    appId: '1:961689273755:android:cb0b433d317537cb3b4d3e',
    messagingSenderId: '961689273755',
    projectId: 'easytravel-b7a06',
    storageBucket: 'easytravel-b7a06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBApMxVxnfBB-UKnvpgKSD8X68wYULCl3M',
    appId: '1:961689273755:ios:48bf3be1edbae3db3b4d3e',
    messagingSenderId: '961689273755',
    projectId: 'easytravel-b7a06',
    storageBucket: 'easytravel-b7a06.appspot.com',
    iosBundleId: 'com.example.easyTravel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBApMxVxnfBB-UKnvpgKSD8X68wYULCl3M',
    appId: '1:961689273755:ios:e4cec1a9f7aceabb3b4d3e',
    messagingSenderId: '961689273755',
    projectId: 'easytravel-b7a06',
    storageBucket: 'easytravel-b7a06.appspot.com',
    iosBundleId: 'com.example.easyTravel.RunnerTests',
  );
}
